// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmIzA5CLwsq3lh5iMbx9JNQfBMJUZheDo',
    appId: '1:487788060214:android:f6298ab5adb3ae0f78c297',
    messagingSenderId: '487788060214',
    projectId: 'bootcamp-607ce',
    storageBucket: 'bootcamp-607ce.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUTnKRFI0jzM7ZHm_dRBIKwMLuIAmF-hk',
    appId: '1:487788060214:web:fdc8f1b1a2ee8a1878c297',
    messagingSenderId: '487788060214',
    projectId: 'bootcamp-607ce',
    authDomain: 'bootcamp-607ce.firebaseapp.com',
    storageBucket: 'bootcamp-607ce.firebasestorage.app',
    measurementId: 'G-4MM5JZC36R',
  );
}
